### ISSUE TITLE
No implementation for `merge()`ing map and multimap/set and multiset

### ISSUE THREAD

**Issue by cmazakas** [boostorg/unordered#103]

**Comment by cmazakas** [comment]
The documentation in the reference is incorrect. These methods actually are implemented, the docs just need to be updated.

**Comment by pdimov** [comment]
Do we have tests for it?

**Comment by cmazakas** [comment]
Yup, those tests live here:
https://github.com/boostorg/unordered/blob/0d3ece98c1eaf4305d8422aad6517f8c924ca763/test/unordered/merge_tests.cpp#L285-L333
