### ISSUE TITLE
implement equal_range for unordered_multimap with template key

### ISSUE THREAD

**Issue by amirhakh** [boostorg/unordered#15]
Dear All

Can you implement template<class K> equal_range like std library?

```C++
template< class K >
std::pair<iterator,iterator> equal_range( const K& x );
```
can read more in:
https://en.cppreference.com/w/cpp/container/unordered_multimap/equal_range

**Comment by cmazakas** [comment]
Hello @amirhakh , this has been added with #61 

I'm going to close this issue now. Feel free to re-open if you have any questions or concerns.
