### ISSUE TITLE
No implementation of P2363

### ISSUE THREAD

**Issue by cmazakas** [boostorg/unordered#150]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2363r3.html

**Comment by iwubcode** [comment]
Yes please.  I would love to see this in time for 1.81!

**Comment by cmazakas** [comment]
This has been implemented and is on develop. I'm going to close the issue.

**Comment by iwubcode** [comment]
Wonderful news.  Thank you!
