### ISSUE TITLE
Forceinline improves performance significantly with MSVC

### ISSUE THREAD

**Issue by sbsce** [boostorg/unordered#168]
While testing `boost::unordered_flat_set`, I noticed my code is reliably running over 10% faster if I `__forceinline` all the function calls that the `boost::unordered_flat_set` makes in my hot path. My hot path is only doing `.contains()`, so anything called by `.contains()`, including the `.contains` itself, is where I added `__forceinline`. So that in my own code where I call `.contains()`, looking at the disassembly there is no `call` anywhere any more, it's fully inlined. I think I had to add `__forceinline` to 6 functions inside boost code.

It is a bit inconvenient to manually add `__forceinline` to all those functions though - it's definitely worth the 10% performance gain, but I am quite sure that the next time I update boost in a few years, I'll forget to apply these changes again, and then my performance will be worse. 

Assuming you don't want to add `__forceinline` to those functions by default, could there maybe some define like `BOOST_FORCEINLINE_UNORDERED_SET` that automatically enables forceinlining all the important functions?

I am already compiling with maximum optimization level of MSVC, so by default it doesn't want to inline it, MSVC often needs to be forced to inline stuff.

**Comment by joaquintides** [comment]
Can you list those Boost-internal 6 functions you inlined?

**Comment by sbsce** [comment]
Sure, here's what I had to change to get it fully inlined, I changed it one by one until the disassembly no longer contained any `call` instruction:

![image](https://user-images.githubusercontent.com/38058738/203003795-af405d24-bfbc-4b40-b718-5ba214b7b63c.png)
![image](https://user-images.githubusercontent.com/38058738/203003479-ee4ba8e9-ac44-4afa-8443-2ba876a6e1e8.png)
![image](https://user-images.githubusercontent.com/38058738/203003588-6d82a025-8871-4cc0-aba9-24d0e5ba1e87.png)

FORCEINLINE is a globally defined macro I have that's just doing `__forceinline`.
