### ISSUE TITLE
Minor extra-semicolon warning issued for clang builds

### ISSUE THREAD

**Issue by hadrielk** [boostorg/unordered#190]
This is a minor nit, but the file `unordered/detail/foa.hpp` has a couple functions with extra semi-colons that trigger `clang`'s `extra-semi` warning:

1. `maybe_caused_overflow()` on line `233`.
2. `~destroy_on_exit()` on line `1719`.

**Comment by cmazakas** [comment]
It's easy to add this check to our CI.

For clarity, you're using this compiler option, correct?
```
-Wextra-semi-stmt
```
