### ISSUE TITLE
Enhancement: unordered_flat_map should static_assert the value_type is move-constructible

### ISSUE THREAD

**Issue by hadrielk** [boostorg/unordered#191]
Unlike `unordered_node_map<>`, the `flat` one requires the `value_type` be move-constructible. (I think? Or perhaps copy-constructible if the type is not move-constructible?)

Unfortunately, if you use a type that is _not_ move-constructible, the compiler generates an enormous wall of cryptic errors instead... because the compilation failure occurs inside of a deep chain of template instantiations.

I think a few `static_assert(std::is_move_constructible<T>::value)`s would be nicer.

**Comment by cmazakas** [comment]
This is simple to do and is a good hardening measure to improve the UX.

We'll get this done soon after the concurrent_flat_map branch is merged in.

**Comment by k3DW** [comment]
After merging #269, now every invalid constructor call will be caught. This is generic for any future use cases, as I have not hard-coded any specific constraints on the containers. A `flat` container will invoke a move constructor, and therefore requires that a move constructor exists and is callable. A `node` container does not do this, so it will not check for move constructibility.
