### ISSUE TITLE
unordered_map iterator stability after reserve

### ISSUE THREAD

**Issue by GuyAv46** [boostorg/unordered#235]
I was trying to replace the standard unordered_map in my code with the boost implementation, but I ran into an instability that caused my test to crash.

I was able to find [minimal reproduction steps](https://godbolt.org/z/KGx9xx6bE). Notice that by replacing the `boost::unordered_map` with `std::unordered_map` at the start, the program succeeds.

I couldn't find any documentation about this, but I was under the impression that Boost's unordered map is a drop-in replacement for the std one.

**Comment by cmazakas** [comment]
All iterators are invalidated after calls to rehash() and reserve().

See the section here on cppreference: https://en.cppreference.com/w/cpp/container/unordered_map#Iterator_invalidation

**Comment by GuyAv46** [comment]
Thanks!
