### ISSUE TITLE
Is erase safe for unordered concurrent structures

### ISSUE THREAD

**Issue by diehard2** [boostorg/unordered#242]
Apologies for a question under issues, but I couldn't find a better place for this. Most (all?) concurrent containers are unsafe on erase. They appear to usually be marked with as 'unsafe_erase'. I can't find any documentation on the boost concurrent container's safety on the erase operation. Is it safe to erase without a lock?

**Comment by joaquintides** [comment]
Yes, `erase` is safe, this is mentioned [here](https://www.boost.org/doc/libs/1_85_0/libs/unordered/doc/html/unordered.html#concurrent_flat_map) (bold mine):

> `boost::concurrent_flat_map` — A hash table that associates unique keys with another value and allows for concurrent element insertion, **erasure**, lookup and access without external synchronization mechanisms.
