### ISSUE TITLE
all tests are broken

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/unordered#26]
Currently all the tests are broken. To be clear: it's not the the library code that's broken, but the tests itself. There are multiples issues:
- somehow the downloaded boost-snapshot doesn't get unpacked (python complains that the downloaded file is not a bz2 file)
- appveyor tries to invoke msvc 10 and 11, which seem to be no longer present ('cl' is not a recognized command)
- travis fails when trying to install 'cpp-coveralls' with pip

**Comment by LeonineKing1199** [comment]
Hi tobias!

Recently, the project was updated to use GitHub Actions and it seems like AppVeyor is now cleaned up as well.

Does this resolve the issue or is there anything else we should be aware of?

**Comment by tobias-loew** [comment]
Hi Leonine,
Thanks for fixing the appveyor tests, but please also have a look at my pr #27 where I used the new boost appveyor script and also implemented tests with GitHub actions and drone.
This work was done in collaboration with @Flamefire and @sdarwin
-- Tobias
