### ISSUE TITLE
std::forward is called twice for the parameter

### ISSUE THREAD

**Issue by NumberEndymion4** [boostorg/unordered#270]
In `unordered_map::emplace(Args&&... args)` and `unordered_set::emplace(Args&&... args)` functions, `std::forward` is called twice for the variadic parameter `args`. This may cause the moved parameter to be used.

**Comment by k3DW** [comment]
In this particular case, there is no actual use-after-move. That said, it's confusing to read the code and see `std::forward` being called twice, so I opened a PR to use `as_const` instead of the first call to `std::forward`.
