### ISSUE TITLE
Missing assignment operator=(std::initializer_list<value_type>)

### ISSUE THREAD

**Issue by tlemo** [boostorg/unordered#276]
The boost.unordered containers are missing the assignment operator taking an `std::initializer_list` argument. While it may seem redundant, this can be needed in a few special cases - in particular when using custom allocators which lack default initialization (as many stateful allocators are)

**Comment by joaquintides** [comment]
Fixed in https://github.com/boostorg/unordered/commit/cd9a592f0036f61f3314a7c3500dcc48228f7900, thanks for the report!
