### ISSUE TITLE
`unordered_map::count()` is missing transparent overload

### ISSUE THREAD

**Issue by LeonineKing1199** [boostorg/unordered#44]
[P1690R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1690r1.html) added a transparent overload of `count()` that avoids creating an intermediate object when getting the count.

See: https://en.cppreference.com/w/cpp/container/unordered_map/count

**Comment by LeonineKing1199** [comment]
One thing I didn't realize until I started development, no one seems to specify the argument order for the `KeyEqual` callable.

The way the library is now, it goes: `eq(user_supplied_type, stored_type)`.

Should we try and support flipping the user-provided `KeyEqual` if the user's `operator==` implementation wasn't written this way?

**Comment by pdimov** [comment]
No.
