### ISSUE TITLE
Interoperability 32/64 sizeof and hashing

### ISSUE THREAD

**Issue by CerosDev** [boostorg/unordered#9]
**Situation**
We are storing a `unordered_map`, `unordered_multi_map` and `unordered_set` in a Boost Interprocess Shared Memory that is accessed by a 32bit process and a 64bit process. The 32bit process or the 64bit process can be the creator of the object.

**Symptoms**
If a 64bit process creates these containers, the 32bit process will crash trying to retrieve it and vice-versa.
If a 64bit process inserts object into one of the containers, the 32bit process will fail to retrieve them by hashing and vice-versa.

**Solution**
I had to modify some headers so that the sizeof of the unordered's implementation is exactly the same in 32 and 64bits. 
In my own code, I force the hashing to be on 32bit instead of `size_t`. There is some issues internally around the policy. It will fall on a different logic and yield different result if on 32bit or 64bit.

See patch attached.
[boost-1.68.0-fix-interoperability-32-64-unordered.patch.zip](https://github.com/boostorg/unordered/files/2572645/boost-1.68.0-fix-interoperability-32-64-unordered.patch.zip)

See related issue for Boost Multi-Index https://github.com/boostorg/multi_index/issues/17

**Comment by joaquintides** [comment]
Hi,

Thanks for the report and congrats on the ingenuity you've used to make this unexpected scenario work. I have to say, though, that 32/64 interprocess compatibility is not (by far) one feature I'm willing to support to the point of fixing the size of internal size-storing variables to either 32 or 64 bits (by the way, your patch seems inconsistent in that some `std::size_t` are converted in some places to `uint64_t` (like `size_` and `capacity_` in `rnd_index_ptr_array.hpp`) and to `uint32_t` in some other (`node_count` in `multi_index_container.hpp`)).

I'm sorry to say you'll have to stick to patching your local copy of Boost to cope with the very exotic scenario you're dealing with.

Best regards,

**Comment by CerosDev** [comment]
What about leaving the flexibility to the user via a template parameter? By default it could remain `std::size_t` and use the SFINAEd policy. Would that be feasible?

**Comment by CerosDev** [comment]
Would it be possible to use the allocator's size_type to change the type of `bucket_count_`, `size_` and `max_load_` and use the allocator's size_type to determine the policy to use?
